name: notification_repository
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_messaging: ^14.2.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0