// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCdL5vcLRamLJucKsjYkSi4-0tsGqlrM',
    appId: '1:1033168644939:web:ac5c7d0428195530a296ce',
    messagingSenderId: '774283908977',
    projectId: 'pn-bloc',
    authDomain: 'push-notifications-be959.firebaseapp.com',
    storageBucket: 'push-notifications-be959.appspot.com',
    measurementId: 'G-LL47KDYMHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCdL5vcLRamLJucKsjYkSi4-0tsGqlrM',
    appId: '1:1033168644939:android:dcb7079a82b16f43a296ce',
    messagingSenderId: '774283908977',
    projectId: 'pn-bloc',
    storageBucket: 'push-notifications-be959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCdL5vcLRamLJucKsjYkSi4-0tsGqlrM',
    appId: '1:774283908977:ios:cfa3f40f024534730ec8d0',
    messagingSenderId: '774283908977',
    projectId: 'pn-bloc',
    storageBucket: 'pn-bloc.appspot.com',
    iosClientId:
        '774283908977-6qjdo1fu738q1sei36t31orm9ci281k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pnBloc',
  );
}
